import {cookies} from "next/headers";
import {NextResponse} from "next/server";
import {AUTH_COOKIES} from "@/lib/auth/cookies";
import {getBackendClient} from "@/lib/backend-client";
import {normalizeBackendError} from "@/lib/server/backend-error";
const FIELDS = ["name", "name_ar", "description", "description_ar", "is_active"] as const;
interface Props {params: Promise<{id: string}>;}
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
async function token() { return (await cookies()).get(AUTH_COOKIES.access)?.value; }
export async function GET(_request: Request, {params}: Props) { const accessToken = await token(); if (!accessToken) return NextResponse.json({code: "UNAUTHENTICATED"}, {status: 401}); const {id} = await params; try { const response = await getBackendClient().get(`/api/super-admin/categories/${id}`, {headers: {Authorization: `Bearer ${accessToken}`}}); return NextResponse.json(response.data, {headers: {"Cache-Control": "no-store"}}); } catch (error) { const normalized = normalizeBackendError(error, "Unable to load category"); return NextResponse.json(normalized.body, {status: normalized.status}); } }
export async function PATCH(request: Request, {params}: Props) { const accessToken = await token(); if (!accessToken) return NextResponse.json({code: "UNAUTHENTICATED"}, {status: 401}); let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({code: "INVALID_JSON"}, {status: 400}); } if (!isRecord(body)) return NextResponse.json({code: "INVALID_CATEGORY"}, {status: 400}); const payload = Object.fromEntries(FIELDS.flatMap((field) => { const value = body[field]; return typeof value === "string" || typeof value === "boolean" || value === null ? [[field, value]] : []; })); if (!Object.keys(payload).length) return NextResponse.json({code: "INVALID_CATEGORY"}, {status: 400}); const {id} = await params; try { const response = await getBackendClient().patch(`/api/super-admin/categories/${id}`, payload, {headers: {Authorization: `Bearer ${accessToken}`}}); return NextResponse.json(response.data, {headers: {"Cache-Control": "no-store"}}); } catch (error) { const normalized = normalizeBackendError(error, "Unable to update category"); return NextResponse.json(normalized.body, {status: normalized.status}); } }
export async function DELETE(_request: Request, {params}: Props) { const accessToken = await token(); if (!accessToken) return NextResponse.json({code: "UNAUTHENTICATED"}, {status: 401}); const {id} = await params; try { const response = await getBackendClient().delete(`/api/super-admin/categories/${id}`, {headers: {Authorization: `Bearer ${accessToken}`}}); return NextResponse.json(response.data, {headers: {"Cache-Control": "no-store"}}); } catch (error) { const normalized = normalizeBackendError(error, "Unable to delete category"); return NextResponse.json(normalized.body, {status: normalized.status}); } }
