"use client";

import {useEffect, useState} from "react";
import {useTranslations} from "next-intl";
import {useCreateCategory, useUpdateCategory} from "@/hook/mutations/use-category-mutations";
import {useSuperAdminCategory} from "@/hook/queries/use-super-admin-categories";
import {Link, useRouter} from "@/i18n/navigation";
import {normalizeApiError} from "@/lib/api-error";

export function CategoryForm({id}: {id?: string}) { const t = useTranslations("Categories"); const common = useTranslations("Common"); const router = useRouter(); const editing = Boolean(id); const {data, isPending, isError, error, refetch} = useSuperAdminCategory(id ?? "", editing); const create = useCreateCategory(); const update = useUpdateCategory(); const [name, setName] = useState(""); const [nameAr, setNameAr] = useState(""); const [description, setDescription] = useState(""); const [descriptionAr, setDescriptionAr] = useState(""); const [active, setActive] = useState(true); const [errors, setErrors] = useState<Record<string, string>>({}); const [formError, setFormError] = useState<string>(); const category = data?.category;
useEffect(() => { if (!category) return; setName(category.name ?? ""); setNameAr(category.name_ar ?? ""); setDescription(category.description ?? ""); setDescriptionAr(category.description_ar ?? ""); setActive(category.is_active); }, [category]);
function first(next: Record<string, string>) { const field = ["name", "name_ar", "description", "description_ar"].find((key) => next[key]); requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-field="${field}"]`)?.querySelector<HTMLInputElement | HTMLTextAreaElement>("input, textarea")?.focus()); }
async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setFormError(undefined); const next: Record<string, string> = {}; if (!name.trim()) next.name = t("nameRequired"); if (Boolean(description.trim()) !== Boolean(descriptionAr.trim())) { if (!description.trim()) next.description = t("pairedRequired"); if (!descriptionAr.trim()) next.description_ar = t("pairedRequired"); } if (Object.keys(next).length) { setErrors(next); first(next); return; } const payload = {name: name.trim(), name_ar: nameAr.trim() || null, description: description.trim() || null, description_ar: descriptionAr.trim() || null, is_active: active}; try { if (editing && category) { await update.mutateAsync({id: id!, payload}); router.replace(`/categories/${id}`); } else { const result = await create.mutateAsync(payload); router.replace(`/categories/${result.category.id}`); } } catch (failure) { const apiError = normalizeApiError(failure); if (Object.keys(apiError.fieldErrors).length) { setErrors(apiError.fieldErrors); first(apiError.fieldErrors); } else setFormError(common(apiError.translationKey)); } }
if (editing && isPending) return <div className="store-form-panel"><div className="table-state">{common("loading")}</div></div>; if (editing && (isError || !category)) return <div className="store-form-panel"><div className="table-state" role="alert"><strong>{t("loadError")}</strong><button className="secondary-button" type="button" onClick={() => refetch()}>{common("retry")}</button></div></div>; const pending = create.isPending || update.isPending;
return <section className="store-form-panel"><form className="store-form" noValidate onSubmit={submit}><div className="store-form-grid"><Field field="name" label={t("name")} value={name} error={errors.name} onChange={setName} /><Field field="name_ar" label={t("nameAr")} value={nameAr} error={errors.name_ar} onChange={setNameAr} dir="rtl" /><Field field="description" label={t("description")} value={description} error={errors.description} onChange={setDescription} textarea /><Field field="description_ar" label={t("descriptionAr")} value={descriptionAr} error={errors.description_ar} onChange={setDescriptionAr} textarea dir="rtl" /><label className="store-active-control"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} />{t("active")}</label></div>{formError ? <p className="error-message" role="alert">{formError}</p> : null}<div className="store-form-actions"><Link className="secondary-button" href={editing ? `/categories/${id}` : "/categories"}>{t("cancel")}</Link><button className="primary-button" type="submit" disabled={pending}>{pending ? t("saving") : editing ? t("save") : t("create")}</button></div></form></section>; }
function Field({field,label,value,error,onChange,textarea,dir}: {field:string;label:string;value:string;error?:string;onChange:(value:string)=>void;textarea?:boolean;dir?:"rtl"}) { return <div className="field store-form-full" data-field={field}><label>{label}</label>{textarea ? <textarea dir={dir} value={value} onChange={(event) => onChange(event.target.value)} /> : <input dir={dir} value={value} onChange={(event) => onChange(event.target.value)} />}{error ? <p className="field-error">{error}</p> : null}</div>; }
