"use client";
import {Pencil} from "lucide-react";
import {useLocale, useTranslations} from "next-intl";
import {useSuperAdminCategory} from "@/hook/queries/use-super-admin-categories";
import {Link} from "@/i18n/navigation";
import {getLocalizedValue} from "@/lib/i18n/get-localized-value";
import {normalizeApiError} from "@/lib/api-error";
import type {SupportedLocale} from "@/i18n/routing";
export function CategoryDetails({id}: {id: string}) { const t = useTranslations("Categories"); const common = useTranslations("Common"); const locale = useLocale() as SupportedLocale; const {data,isPending,isError,error,refetch} = useSuperAdminCategory(id); if (isPending) return <section className="product-details-panel"><div className="table-state">{common("loading")}</div></section>; if (isError || !data) { const apiError = normalizeApiError(error); return <section className="product-details-panel"><div className="table-state" role="alert"><strong>{t("loadError")}</strong><p>{common(apiError.translationKey)}</p><button className="secondary-button" type="button" onClick={() => refetch()}>{common("retry")}</button></div></section>; } const category = data.category; const name = getLocalizedValue({localized: category.name_i18n, locale, fallback: category.name}) || t("unnamed"); const description = getLocalizedValue({localized: category.description_i18n, locale, fallback: category.description}) || t("notAvailable"); return <section className="product-details-panel"><header className="product-details-header"><div className="product-details-identity"><div><h2 dir="auto">{name}</h2><span className={`store-status ${category.is_active ? "active" : "inactive"}`}>{category.is_active ? t("active") : t("inactive")}</span></div></div><div className="store-detail-actions"><Link className="primary-button" href={`/categories/${id}/edit`}><Pencil size={18}/>{t("edit")}</Link></div></header><section className="product-details-section"><h3>{t("details")}</h3><div className="product-details-grid"><Item label={t("name")} value={category.name}/><Item label={t("nameAr")} value={category.name_ar || t("notAvailable")}/><Item label={t("slug")} value={category.slug}/><Item label={t("status")} value={category.is_active ? t("active") : t("inactive")}/><Item label={t("description")} value={description}/></div></section></section>; }
function Item({label,value}: {label:string;value:string}) { return <div className="product-details-item"><span>{label}</span><strong dir="auto">{value}</strong></div>; }
